### ISSUE TITLE
Package is not installable from pypi

### ISSUE THREAD

**Issue by skirpichev** [logpy/logpy#38]
```
$ pip install logpy
Downloading/unpacking logpy
  Downloading LogPy-1.0.tar.gz
  Running setup.py egg_info for package logpy
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/sk/.virtualenvs/test/build/logpy/setup.py", line 6, in <module>
        long_description = open('README.rst').read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/sk/.virtualenvs/test/build/logpy/setup.py", line 6, in <module>

    long_description = open('README.rst').read(),

IOError: [Errno 2] No such file or directory: 'README.rst'
```

It seems, this is fixed in the master.

**Comment by hcarvalhoalves** [comment]
It's missing a `MANIFEST.in` file to include README in the package.

**Comment by lucaswiman** [comment]
This seems to have been resolved.
