### ISSUE TITLE
TypeError: 'Var' object is not subscriptable

### ISSUE THREAD

**Issue by kootenpv** [logpy/logpy#58]
Given this implementation ([link](http://log.liminastudio.com/programming/a-python-solution-to-the-zebra-problem-using-logic-programming)):

```python
def lefto(q, p, list):
        # give me q such that q is left of p in list
        # zip(list, list[1:]) gives a list of 2-tuples of neighboring combinations
        # which can then be pattern-matched against the query
        return membero((q,p), zip(list, list[1:]))
```

We get:

```python
<ipython-input-49-52f501fbe475> in lefto(q, p, list)
      3         # zip(list, list[1:]) gives a list of 2-tuples of neighboring combinations
      4         # which can then be pattern-matched against the query
----> 5         return membero((q,p), zip(list, list[1:]))

TypeError: 'Var' object is not subscriptable
```

Using **Python 3** and:

    >>> kanren.__version__
    '0.2.2'

**Comment by lucaswiman** [comment]
Running this through git-bisect, it appears I introduced this bug in 4cc6660be4a6be0bdd85900baf344d293b4948c7, as can be seen by the following:
```sh
~/opensource/logpy $ python ./github_issue_58.py 
Traceback (most recent call last):
  File "./github_issue_58.py", line 64, in <module>
    (membero,       (var(), var(), var(), 'zebra', var()), houses)
  File "/Users/lucaswiman/opensource/logpy/logpy/core.py", line 59, in lall
    return (lallgreedy,) + tuple(earlyorder(*goals))
  File "/Users/lucaswiman/opensource/logpy/logpy/core.py", line 150, in earlyorder
    groups = groupby(earlysafe, goals)
  File "/Users/lucaswiman/.pyenv/versions/2.7/lib/python2.7/site-packages/toolz/itertoolz.py", line 93, in groupby
    d[key(item)](item)
  File "/Users/lucaswiman/opensource/logpy/logpy/core.py", line 134, in earlysafe
    goaleval(goal)
  File "/Users/lucaswiman/opensource/logpy/logpy/core.py", line 280, in goaleval
    egoal = goalexpand(goal)
  File "/Users/lucaswiman/opensource/logpy/logpy/core.py", line 265, in goalexpand
    tmp = goalt[0](*goalt[1:])
  File "./github_issue_58.py", line 15, in lefto
    return membero((q,p), zip(list, list[1:]))
TypeError: 'Var' object has no attribute '__getitem__'
~/opensource/logpy $ git checkout HEAD~1
Previous HEAD position was 4cc6660... Add tests for core methods and rename lall implementations.
HEAD is now at 77e6827... Simplify Var and use __slots__ for efficiency.
~/opensource/logpy $ python ./github_issue_58.py 
1 solutions in 11.64 seconds
The German is the owner of the zebra
Here are all the houses:
('Norwegian', 'Dunhill', 'water', 'cats', 'yellow')
('Dane', 'Blend', 'tea', 'horse', 'blue')
('Englishman', 'Pall Mall', 'milk', 'birds', 'red')
('German', 'Prince', 'coffee', 'zebra', 'green')
('Swede', 'Blue Master', 'beer', 'dog', 'white')
```


```python
~/opensource/logpy $ cat ./github_issue_58.py 
try:
    from logpy import *
    from logpy.core import lall
    import time
except ImportError:
    from kanren import *
    from kanren.core import lall
    import time


def lefto(q, p, list):
        # give me q such that q is left of p in list
        # zip(list, list[1:]) gives a list of 2-tuples of neighboring combinations
        # which can then be pattern-matched against the query
        return membero((q,p), zip(list, list[1:]))

def nexto(q, p, list):
        # give me q such that q is next to p in list
        # match lefto(q, p) OR lefto(p, q)
        # requirement of vector args instead of tuples doesn't seem to be documented
        return conde([lefto(q, p, list)], [lefto(p, q, list)])

houses = var()

zebraRules = lall(
        # there are 5 houses
        (eq,            (var(), var(), var(), var(), var()), houses),
        # the Englishman's house is red
        (membero,       ('Englishman', var(), var(), var(), 'red'), houses),
        # the Swede has a dog
        (membero,       ('Swede', var(), var(), 'dog', var()), houses),
        # the Dane drinks tea
        (membero,       ('Dane', var(), 'tea', var(), var()), houses),
        # the Green house is left of the White house
        (lefto,         (var(), var(), var(), var(), 'green'),
                                (var(), var(), var(), var(), 'white'), houses),
        # coffee is the drink of the green house
        (membero,       (var(), var(), 'coffee', var(), 'green'), houses),
        # the Pall Mall smoker has birds
        (membero,       (var(), 'Pall Mall', var(), 'birds', var()), houses),
        # the yellow house smokes Dunhills
        (membero,       (var(), 'Dunhill', var(), var(), 'yellow'), houses),
        # the middle house drinks milk
        (eq,            (var(), var(), (var(), var(), 'milk', var(), var()), var(), var()), houses),
        # the Norwegian is the first house
        (eq,            (('Norwegian', var(), var(), var(), var()), var(), var(), var(), var()), houses),
        # the Blend smoker is in the house next to the house with cats
        (nexto,         (var(), 'Blend', var(), var(), var()),
                                (var(), var(), var(), 'cats', var()), houses),
        # the Dunhill smoker is next to the house where they have a horse
        (nexto,         (var(), 'Dunhill', var(), var(), var()),
                                (var(), var(), var(), 'horse', var()), houses),
        # the Blue Master smoker drinks beer
        (membero,       (var(), 'Blue Master', 'beer', var(), var()), houses),
        # the German smokes Prince
        (membero,       ('German', 'Prince', var(), var(), var()), houses),
        # the Norwegian is next to the blue house
        (nexto,         ('Norwegian', var(), var(), var(), var()),
                                (var(), var(), var(), var(), 'blue'), houses),
        # the house next to the Blend smoker drinks water
        (nexto,         (var(), 'Blend', var(), var(), var()),
                                (var(), var(), 'water', var(), var()), houses),
        # one of the houses has a zebra--but whose?
        (membero,       (var(), var(), var(), 'zebra', var()), houses)
)

t0 = time.time()
solutions = run(0, houses, zebraRules)
t1 = time.time()
dur = t1-t0

count = len(solutions)
zebraOwner = [house for house in solutions[0] if 'zebra' in house][0][0]

print "%i solutions in %.2f seconds" % (count, dur)
print "The %s is the owner of the zebra" % zebraOwner
print "Here are all the houses:"
for line in solutions[0]:
        print str(line)

~/opensource/logpy $ git checkout 4cc6660be4a6be0bdd85900baf344d293b4948c7
Previous HEAD position was 77e6827... Simplify Var and use __slots__ for efficiency.
HEAD is now at 4cc6660... Add tests for core methods and rename lall implementations.
```

**Comment by lucaswiman** [comment]
I'll work on simplifying this example into a small testcase, and then investigate a fix. No guarantees when that'll be, so patches definitely welcome. 😄

**Comment by kootenpv** [comment]
Perfect case for using git bisect! I'm really hope for a patch, I'm really want to use this code as a basis for something awesome!

If you do not have an idea how to patch, do you have an alternate way of accomplishing the same with the current version of `kanren`?

**Comment by lucaswiman** [comment]
> If you do not have an idea how to patch, do you have an alternate way of accomplishing the same with the current version of `kanren`?

Yes! The bug is in the `membero` goal being evaluated too early. The implementation of `lall` _should_ be able to handle that, but you can get around the bug by letting it evaluate the goal later on:
```python
def lefto(q, p, list):
        # give me q such that q is left of p in list
        # zip(list, list[1:]) gives a list of 2-tuples of neighboring combinations
        # which can then be pattern-matched against the query
        return (membero, (q,p), zip(list, list[1:]))

def nexto(q, p, list):
        # give me q such that q is next to p in list
        # match lefto(q, p) OR lefto(p, q)
        # requirement of vector args instead of tuples doesn't seem to be documented
        return (conde, [lefto(q, p, list)], [lefto(p, q, list)])
```

**Comment by kootenpv** [comment]
Thanks for giving it a look. I replaced the two functions, but still I get the same error. Here's a trace:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-5e9ed6c73287> in <module>()
     38                                 (var(), var(), 'water', var(), var()), houses),
     39         # one of the houses has a zebra--but whose?
---> 40         (membero,       (var(), var(), var(), 'zebra', var()), houses)
     41 )

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kanren/core.py in lall(*goals)
     51     (2, 3)
     52     """
---> 53     return (lallgreedy, ) + tuple(earlyorder(*goals))
     54 
     55 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kanren/core.py in earlyorder(*goals)
    153     if not goals:
    154         return ()
--> 155     groups = groupby(earlysafe, goals)
    156     good = groups.get(True, [])
    157     bad = groups.get(False, [])

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/toolz/itertoolz.py in groupby(key, seq)
     91     d = collections.defaultdict(lambda: [].append)
     92     for item in seq:
---> 93         d[key(item)](item)
     94     rv = {}
     95     for k, v in iteritems(d):

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kanren/core.py in earlysafe(goal)
    136     """ Call goal be evaluated without raising an EarlyGoalError """
    137     try:
--> 138         goaleval(goal)
    139         return True
    140     except EarlyGoalError:

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kanren/core.py in goaleval(goal)
    298         return goal
    299     if isinstance(goal, tuple):  # goal is not yet evaluated like (eq, x, 1)
--> 300         return find_fixed_point(evalt, goal)
    301     raise TypeError("Expected either function or tuple")

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kanren/core.py in find_fixed_point(f, arg)
    283     while last != cur:
    284         last = cur
--> 285         cur = f(cur)
    286     return cur
    287 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kanren/util.py in evalt(t)
     82 
     83     if isinstance(t, tuple) and len(t) >= 1 and callable(t[0]):
---> 84         return t[0](*t[1:])
     85     else:
     86         return t

<ipython-input-16-f1ac24a502a6> in lefto(q, p, list)
      3         # zip(list, list[1:]) gives a list of 2-tuples of neighboring combinations
      4         # which can then be pattern-matched against the query
----> 5         return (membero, (q,p), zip(list, list[1:]))

TypeError: 'Var' object is not subscriptable
```

**Comment by lucaswiman** [comment]
Minimal simplification of the "zebra", which clearly should have a unique solution, but fails with the `'Var' object is not subscriptable` error:
```python
def test_goal_ordering():
    # Regression test for https://github.com/logpy/logpy/issues/58

    def lefto(q, p, lst):
        return membero((q, p), zip(lst, lst[1:]))

    vals = var()
    rules = (
        lall,
        (eq, (var(), var()), vals),
        (lefto, 'green', 'white', vals),
    )

    solution, = run(1, vals, rules)
```

**Comment by lucaswiman** [comment]
@kootenpv I deployed the new version to pypi. Try it now.

**Comment by kootenpv** [comment]
It worked, thanks! It's nice to see it was handled so professionally! I'll let you know when I've experimented more with `kanren` :)
